import { Suspense } from "react"
import "./globals.css"
import { Figtree } from "next/font/google"
import type { Metadata } from "next"
import Provider from "./provider"
import Loading from "./loading"

export const metadata: Metadata = {
	title: "SolarInfo",
	description: "Generated by create next app",
}

const figtree = Figtree({
	subsets: ["latin"],
	display: "swap",
})

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className={`${figtree.className}`} suppressHydrationWarning>
			<body>
				<Provider>
					<Suspense fallback={<Loading />}>{children}</Suspense>
				</Provider>
			</body>
		</html>
	)
}
